# Generated by Django 3.2.2 on 2021-05-19 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('C', 'Completed'), ('Q', 'Queueing'), ('R', 'Running')], max_length=1)),
                ('job_id', models.CharField(blank=True, max_length=20)),
            ],
        ),
    ]
