# Generated by Django 3.2.2 on 2021-05-30 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_job_resources'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='software',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
