# Generated by Django 3.2.2 on 2021-07-05 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_job_software'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('script_lines', models.TextField(help_text='Lines placed here are used as scheduler directives for new jobs.', max_length=1000, verbose_name='Script Lines')),
            ],
        ),
    ]
