# Generated by Django 3.2.2 on 2021-07-06 10:59

from django.db import migrations, models
import main.validators


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_customconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customconfig',
            name='script_lines',
            field=models.TextField(help_text='Lines placed here are used as scheduler directives for new jobs.', max_length=1000, validators=[main.validators.validate_config_lines], verbose_name='Script Lines'),
        ),
    ]
