# Generated by Django 3.2.2 on 2021-07-12 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_customconfig_script_lines'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='_walltime',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
