# Generated by Django 4.0.1 on 2022-03-02 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20220302_0820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='refresh_token',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AlterField(
            model_name='token',
            name='value',
            field=models.CharField(max_length=240),
        ),
    ]
