on: push
jobs:
  qa:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4.1.0
        with:
          python-version: 3.9
      - uses: pre-commit/action@v2.0.3
  testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4.1.0
        with:
          python-version: 3.9
      - name: Install prerequisites
        run: |
          python -m pip install -q -U pip
          python -m pip install -q -r requirements.txt
      - name: Run tests
        run: |
          PORTAL_CONFIG_PATH=./main/tests/test_data/test_config.yaml python manage.py test --no-input
  demo_cluster:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests in demo cluster
        run: |
          docker-compose -f demo_cluster/docker-compose.demo.yaml run --rm ondemand bash demo_cluster/run_test.sh
